---
creation_rules:
  - path_regex: .*secret\.sops\.ya?ml$
    key_groups:
      - age:
          - age1zeqkpfz7e3s207ynea0z0auc0mrct0pc7w4sh6j3d0c4qac3dahqj9ufdg
          - age1tdwlq9y4jgejkhasqwynw5uaen9xwatcvr52l70trsdxkeyvlesqjnh7l8
          - age1n92q5j8s9v9sq4waj32ztgghvgg77u6kemsc93q5l6tmkjy3cpjq627f2q
