[tokyonight-gtk-theme]
src.git = "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme"
fetch.git = "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme"
[tokyonight-icon-theme]
src.git = "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme"
fetch.git = "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme"
[chezmoi-vim]
src.git = "https://github.com/alker0/chezmoi.vim"
fetch.git = "https://github.com/alker0/chezmoi.vim"
[mason-lspconfig-nvim]
src.git = "https://github.com/williamboman/mason-lspconfig.nvim"
fetch.git = "https://github.com/williamboman/mason-lspconfig.nvim"
[mason-tool-installer-nvim]
src.git = "https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim"
fetch.git = "https://github.com/WhoIsSethDaniel/mason-tool-installer.nvim"
[lir-git-status-nvim]
src.git = "https://github.com/tamago324/lir-git-status.nvim"
fetch.git = "https://github.com/tamago324/lir-git-status.nvim"
