apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 
  namespace: flux-system
spec:
  path: ./cluster/
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
